ALTER DEFAULT PRIVILEGES FOR ROLE postgres
    GRANT SELECT ON SEQUENCES TO read;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres
    GRANT SELECT, USAGE ON SEQUENCES TO write;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
    GRANT SELECT ON TABLES TO read;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO write;
